### ISSUE TITLE
Dependencies? Merge?

### ISSUE THREAD

**Issue by Syphurith** [felipejfc/ygw-eshop-spoofer#2]
This depends on [ctrcommon](https://github.com/Steveice10/ctrcommon). ctrcommon requires [devkitARM](http://sourceforge.net/projects/devkitpro/files/devkitARM/), [aemstro](https://github.com/smealum/aemstro), and [ctrulib](https://github.com/smealum/ctrulib) to build. Well and [libkhax](https://github.com/Myriachan/libkhax). libctru requires nothing more than devkitARM.
Since there is `svcBackdoor` function used in YGW, I searched all those sources for such a symbol, which turns out to be in libctru. But there is only the definition and no implemention found.

~~I'm thinking of port/merge this to Pasta.~~ You used `ctrcommon` which then use `libkhax`. So this is happened in ARM11 scope not Pasta's ARM9 one. Well..

**Orz** Your simply copied some code to your `Region-Free` repo.. Those are both patchers why don't you just add the feature and give/get a new repo name? You can just create a new branch.
I've already tried to merge these two abilities, checkout my `merge` branch.
~~Still merge all those ARM11 patches may be possible.~~ Turns out to be eh some confusing.

**Comment by Syphurith** [comment]
Well since Braham retrieved a ARM11 Kernel before take the ARM9 one..
I doubt if this could be port to Braham or even Mset, that would mean it is merged into the CFW.

**Comment by felipejfc** [comment]
I'm thinking of merging the two ygw tools into one...

But I ask myself if it worth the time to make it since the final goal is to merge the 2 functions directly into pasta itself...

**Comment by Syphurith** [comment]
@felipejfc Braham own an ARM11 kernel first before it jumps to ARM9. In `s32 firm_reboot (void)` from `braham.c`. I just don't know if we can do some patches there, before `svcCorruptedCreateThread` and after `corrupt_svcCreateThread`. If so then just try to read the configuration file before that.

**Comment by Syphurith** [comment]
@felipejfc [Here](http://gbatemp.net/threads/pasta-cfw-a-cfw-that-allows-unsigned-cia-to-be-installed-on-old-and-new-3ds-required-ninjhax.388925/page-300#post-5557024) a guy did so, he merged both into one.

**Comment by Syphurith** [comment]
@felipejfc Since `free-multi-patcher` is already out, pulls/issues from me are closed. Also the repo.
